# Generated by Django 3.0.8 on 2022-02-05 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='wsyg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
