# Generated by Django 3.0.8 on 2022-04-10 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
